### PR TITLE
Make FluentBit -> ElasticSearch work

### PR DESCRIPTION
**Pull request by kim-cc**
### Description
A few things is fixed in this PR:
* Logs weren't correct sent to ElasticSearch as FluentBit wasn't correctly configured to trust the ElasticSearch certificate.
* ECK operator was correctly updated to 1.8.0 (previosuly it couldn't start because of missing CRDs)
* Few improves to the deployment scripts

The commits should be fairly well structured, so it might be easier to look at the individual commits.

These changes can be tested by deploying everything to a cluster, and check if logs are received by ElasticSearch.

### Relevant Issues/PRs
Issue #262 

### Type(s) of Change (Split the PR if you check many)
- [ ] Added user feature
- [ ] Added technical feature
- [ ] Added tests
- [ ] Refactor
- [X] Bugfix
- [ ] Updated documentation
- [X] Kubernetes changes
- [ ] CI/CD workflow changes

### Testing Checklist
- [ ] I have added/updated unit tests for functional changes.
- [ ] I have added/updated integration tests for changes that affect dependent systems.
- [ ] I have added/updated end-to-end tests for feature changes.

### General Checklist
- [X] I have pulled in the latest changes from master.
- [ ] I have run `make lint`.
- [ ] I have successfully run `make tests`.
- [ ] I have updated relevant CI/CD workflows.
- [X] I have updated relevant Kubernetes manifests/scripts.
- [ ] I have updated/added relevant (internal and external) documentation (readme, doc comments, etc).
- [ ] I have updated the dependency map to reflect my changes.
- [ ] I have added the license to new source code files.
- [X] I have spent some time looking over the full diff before creating this PR.

### CODE REVIEW

**Review by philip-cc — COMMENTED** [review]
We should probably update elasticsearch to 7.16.2 while we're at it.

**Comment by kim-cc** [comment]
> We should probably update elasticsearch to 7.16.2 while we're at it.

@philip-cc Done

**Comment by kim-cc** [comment]
@philip-cc We now also get logs from CockroachDB

**Review by philip-cc — APPROVED** [review]
Looks like we're getting all the logs now :+1:

**Pull request merged**
